findfriends/urls.py
from django.urls import path

from . import views

app_name = 'findfriends'

urlpatterns = [
    path('searchfriends/', views.searchfriends, name='searchfriends'),
    path('friendlist/', views.friendlist, name='friendlist'),
]

findterest_app/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('curhat/', include('curhat.urls')),
    path('findfriends/', include('findfriends.urls')),
    path('contribute/', include('contribute.urls')),
    path('jawab/', include('jawab.urls')),
    path('tanya/', include('tanya.urls')),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

findfriends/models.py
from django.db import models

# Create your models here.
TAHUN = [
    ('2020', '2020'),
    ('2019', '2019'),
    ('2018', '2018'),
    ('2017', '2017'),
    ('2016', '2016'),
    ('2015', '2015'),
    ('Alumni', 'Alumni'),
]

class Find(models.Model):
    
    tahun = models.CharField(max_length=20, choices=TAHUN)

    

findfriends/forms.py
from django import forms
from .models import Find
from contribute.models import ContributeModel

class Findform(forms.ModelForm):
    class Meta:
        model = ContributeModel
        fields = ['major', 'university']

        labels = {
            'university' : 'Your friends current / last university', 'major' : 'Your friends current / last major',
        }
        widgets = {
            'university' : forms.TextInput(attrs={'class': 'form-control',
                                        'type' : 'text',
                                        'placeholder' : 'University'}),

            'major' : forms.TextInput(attrs={'class' : 'form-control',
                                        'type' : 'text',
                                        'placeholder' : 'Major'}),

        }
class TahunForm(forms.ModelForm):
    class Meta:
        model = Find
        fields = ['tahun']

        labels = {
            'tahun' : 'Year of Entry',
        }

findfriends/views.py
from django.shortcuts import render, redirect
from .forms import Findform, TahunForm
from .models import Find
from contribute.models import ContributeModel

# Create your views here.
def searchfriends(request):
    form = Findform()
    formtahun = TahunForm()
    if request.method == "POST":
        form = Findform(request.POST)
        if form.is_valid():
            return redirect('/friendlist/')
    else:
        form = Findform()

    return render(request, 'search.html', {'form' : form, 'formtahun' : formtahun})

def friendlist(request):
    form = Findform(request.POST)
    formtahun = TahunForm(request.POST)
    tahun = formtahun['tahun'].value()
    univ = form['university'].value()
    jurusan = form['major'].value()
    hasil = ContributeModel.objects.filter(university=univ, year_of_entry_cont=str(tahun), major=jurusan)
    return render(request, 'list.html', {'form' : form, 'formtahun' : formtahun, 'hasil' : hasil})

findfriends/templates/list.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Friend List</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="{% static 'findfriend/css/ff.css' %}">
{% endblock %}

{% block content %}
<section>
    <h1>Hasil Pencarian</h1>
    <p>Semoga ada teman yang sesuai :)</p>

    <div class="parent-card">
        {% for i in hasil %}
        <div class="card">
            <h3><strong>{{ i.name }}</strong></h3>
            <p id="list"><img src="https://secure.webtoolhub.com/static/resources/icons/set112/6f62880a.png" width="30px" height="30px"> {{ i.interest }}</p>
            <p id="list"><img src="https://i.pinimg.com/originals/b1/b7/de/b1b7de37299d6d589ba3d7e28652869b.png" width="30px" height="30px"> {{ i.university }}</p>
            <p id="list"><img src="https://images.squarespace-cdn.com/content/v1/5b1ae9562714e50c82575441/1584552166051-TYLHWF4YNUQ3CUO98U2O/ke17ZwdGBToddI8pDm48kGfiFqkITS6axXxhYYUCnlRZw-zPPgdn4jUwVcJE1ZvWQUxwkmyExglNqGp0IvTJZUJFbgE-7XRK3dMEBRBhUpxQ1ibo-zdhORxWnJtmNCajDe36aQmu-4Z4SFOss0oowgxUaachD66r8Ra2gwuBSqM/100-512.png" width="30px" height="30px"> {{ i.social_media }}</p>

        </div>
        {% endfor %}
    </div>
</section>


{% endblock %}

findfriends/templates/search.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Search Friend</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="{% static 'main/css/lending-page.css' %}">
<link rel="stylesheet" href="{% static 'findfriend/css/ff.css' %}">
{% endblock %}

{% block content %}
<section class="src">
    <div id="judul" class="kiri">
        <h1><label class="biru" for="">Find </label>Friends</h1>
        <h2>Carilah temanmu berdasarkan kategori berikut :</h2>
        <div class="serc">
            <form method="POST" action="{% url 'findfriends:friendlist' %}">
                {% csrf_token %}
                <label for="name">{{ form.university.label_tag }}</label><br>
                {{ form.university }}
                <br><br>
                <label for="name">{{ formtahun.tahun.label_tag }}</label><br>
                {{ formtahun.tahun }}
                <br><br>
                <label for="name">{{ form.major.label_tag }}</label><br>
                {{ form.major }}
                <br><br>
                <button type="submit" value="Save" class="button"><h4>SEARCH</h4></button>
            </form>
        </div>
    </div>

    <div class="kanan">
        <img src="{% static 'findfriend/card1.svg' %}" alt="" style="width: 40vmax; height: 40vmax;">
    </div>
</section>

{% endblock %}