findfriends/urls.py
from django.urls import path

from . import views

app_name = 'findfriends'

urlpatterns = [
    path('searchfriends/', views.searchfriends, name='searchfriends'),
    path('friendlist/', views.friendlist, name='friendlist'),
]

findterest_app/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('curhat/', include('curhat.urls')),
    path('findfriends/', include('findfriends.urls')),
    path('contribute/', include('contribute.urls')),
    path('jawab/', include('jawab.urls')),
    path('tanya/', include('tanya.urls')),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <title>findterest</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/basic.css' %}">
  <link rel="icon" href="/static/asset/findterest_icon.svg" type="image/x-icon">
  
  {% block meta %}
  {% endblock %}
</head>

<body id="body">
  <nav>
    <a href="{% url 'main:home' %}"><img src="{% static 'asset/findterest_logo.svg' %}" alt=""></a>
    <img class="mobile burger" src="{% static 'asset/burger.svg' %}" alt="">
    <div class="menu desktop">
      <a href="{% url 'findfriends:searchfriends' %}">
        <h4>find friends</h4>
      </a>
      <a href="/contribute/">
        <h4>contribute</h4>
      </a>
      <a href="/curhat">
        <h4>curhat</h4>
      </a>
      <a href="/tanya">
        <h4>tanya</h4>
      </a>
      <a href="/jawab">
        <h4>jawab</h4>
      </a>
    </div>

    <div class="burger-menu mobile burger-hide" id="burger-menu">
      <a href="{% url 'findfriends:searchfriends' %}">
        <h4>find friends</h4>
      </a>
      <a href="/contribute/">
        <h4>contribute</h4>
      </a>
      <a href="/curhat">
        <h4>curhat</h4>
      </a>
      <a href="/tanya">
        <h4>tanya</h4>
      </a>
      <a href="/jawab">
        <h4>jawab</h4>
      </a>
    </div>
  </nav>
  {% block content %}
  {% endblock content %}

  <footer>
    <p><b>Copyright ©2020 All rights reserved
        <br>
        This website is made by E05 Group</b></p>
  </footer>

  <script src="/static/script/navbar.js"></script>
</body>

</html>